CHAPTER-2 INTRODUCTION TO NUMPY
==========================

In [1]:
import numpy

numpy.__version__

'1.22.0'

In [2]:
import numpy as np

In [3]:
#np.TAB- KEY

In [4]:
np?

Creating Arrays from Python List
--------------------------------

In [5]:
import numpy as np
np.array([1,12,8,9])

array([ 1, 12,  8,  9])

In [6]:
np.array([3.14,4,6,3])

array([3.14, 4.  , 6.  , 3.  ])

In [7]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [8]:
np.array([range(i,i+3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Array from scratch
-------------------------

In [9]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
np.random.random((3,3))

array([[0.3647541 , 0.10418189, 0.52366477],
       [0.74734838, 0.23894047, 0.3149935 ],
       [0.87683362, 0.65833577, 0.15121944]])

In [15]:
np.random.randint(0,10,(3,3))

array([[5, 9, 7],
       [0, 7, 7],
       [8, 5, 1]])

In [16]:
np.random.normal(0,10,(3,3))

array([[ -4.72110508,  -0.78854899,  12.77920813],
       [-13.72428062,   0.13758373,  -2.70288769],
       [ -2.20027461,  -5.43611631,  -6.57798615]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.empty(3)

array([1., 1., 1.])

Numpy Standard Data Types
-----------------------

In [19]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Data type               -----------------Description

bool_   Boolean (True or False) stored as a byte

int_  Default integer type (same as C long; normally either int64 or int32)

intc  Identical to C int (normally int32 or int64)

intp   Integer used for indexing (same as C ssize_t; normally either int32 or int64)

int8  Byte (–128 to 127)

int16  Integer (–32768 to 32767)

int32  Integer (–2147483648 to 2147483647)

int64  Integer (–9223372036854775808 to 9223372036854775807)

uint8 Unsigned integer (0 to 255)

uint16 Unsigned integer (0 to 65535)

uint32 Unsigned integer (0 to 4294967295)

uint64 Unsigned integer (0 to 18446744073709551615)

float_ Shorthand for float64

float16 Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa

float32 Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa

float64 Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa

complex_ Shorthand for complex128

complex64 Complex number, represented by two 32-bit floats

complex128 Complex number, represented by two 64-bit floats

The Basics of Numpy Arrays
---------------------

In [20]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [21]:
x1 #One - dimensional array

array([5, 0, 3, 3, 7, 9])

In [22]:
x2 #two - dimensional array

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [23]:
x3   #three - dimensional array

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [24]:
x2.shape

(3, 4)

In [25]:
x3.ndim

3

In [26]:
x1.size

6

In [27]:
print("dtype:" , x3.dtype)

dtype: int32


In [28]:
print("itemsize:", x2.itemsize)

itemsize: 4


In [29]:
print("nbytes",x2.nbytes)

nbytes 48


Array Indexing:Accessing Single Elements
---------------------

In [30]:
x1

array([5, 0, 3, 3, 7, 9])

In [31]:
x1[0]

5

In [32]:
x1[-1]

9

In [33]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [34]:
x2[0,0]

3

In [35]:
x2[2,0]

1

In [36]:
x2[2,-1]

7

In [37]:
#modify values

In [38]:
x2[0,0] = 12

In [39]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [40]:
x1[0]= 3.1415 #THIS WILL TRUNCATED 

In [41]:
x1

array([3, 0, 3, 3, 7, 9])

Array Slicing :Accessing Subarrays
-------

In [42]:
# x[start:stop:step]

In [43]:
x =np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x[:5]

array([0, 1, 2, 3, 4])

In [45]:
x[5:]

array([5, 6, 7, 8, 9])

In [46]:
x[0:5]

array([0, 1, 2, 3, 4])

In [47]:
x[::2]

array([0, 2, 4, 6, 8])

In [48]:
x[0::2]

array([0, 2, 4, 6, 8])

In [49]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [50]:
x[6::-2]

array([6, 4, 2, 0])

Multidimensional subarrays
------------------------

In [51]:
x2 = np.random.randint(10,size=(3,3))

In [52]:
x2

array([[4, 3, 4],
       [4, 8, 4],
       [3, 7, 5]])

In [53]:
x2[:2,:3] #two rows, three columns

array([[4, 3, 4],
       [4, 8, 4]])

In [54]:
x2[:3,::2]

array([[4, 4],
       [4, 4],
       [3, 5]])

In [55]:
#subarray dimensions can even be reversed together:
x2[::-1,::-1]

array([[5, 7, 3],
       [4, 8, 4],
       [4, 3, 4]])

Accessing array rows and columns.
---------------------------
One commonly needed routine is accessing single
rows or columns of an array. You can do this by combining indexing and slicing,
using an empty slice marked by a single colon (:):

In [56]:
print(x2[:,0]) #first column of x2

[4 4 3]


In [57]:
print(x2[0]) #first row of x2

[4 3 4]


Subarrays as no-copy views
---------------------------
One important—and extremely useful—thing to know about array slices is that they
return views rather than copies of the array data. This is one area in which NumPy
array slicing differs from Python list slicing: in lists, slices will be copies. Consider our
two-dimensional array from before:

In [58]:
print(x2)

[[4 3 4]
 [4 8 4]
 [3 7 5]]


In [59]:
x2_sub = x2[:2,:2]

In [60]:
x2_sub

array([[4, 3],
       [4, 8]])

In [61]:
x2_sub[0,0] = 99

In [62]:
x2_sub

array([[99,  3],
       [ 4,  8]])

In [63]:
print(x2)

[[99  3  4]
 [ 4  8  4]
 [ 3  7  5]]


Creating copies of arrays
-------------------
Despite the nice features of array views, it is sometimes useful to instead explicitly
copy the data within an array or a subarray. This can be most easily done with the
copy() method:

In [64]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  3]
 [ 4  8]]


In [65]:
x2_sub_copy[0,0] = 12
print(x2_sub_copy)

[[12  3]
 [ 4  8]]


In [66]:
print(x2)

[[99  3  4]
 [ 4  8  4]
 [ 3  7  5]]


Reshaping of Arrays
-------------------
Another useful type of operation is reshaping of arrays. The most flexible way of
doing this is with the reshape() method. For example, if you want to put the num‐
bers 1 through 9 in a 3×3 grid, you can do the following:

In [67]:
grid = np.arange(1,10).reshape((3,3))

In [68]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
grid.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [71]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [72]:
x[np.newaxis,:]

array([[1, 2, 3]])

Array Concatenation and Splitting
----------------------------

All of the preceding routines worked on single arrays. It’s also possible to combine
multiple arrays into one, and to conversely split a single array into multiple arrays.
We’ll take a look at those operations here.

Concatenation of arrays
----------------------

Concatenation, or joining of two arrays in NumPy, is primarily accomplished
through the routines np.concatenate, np.vstack, and np.hstack. np.concatenate
takes a tuple or list of arrays as its first argument, as we can see here:

In [73]:
import numpy as np
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [74]:
z = np.array([12,12,12])
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 12 12 12]


In [75]:
#np.concatenate can also be used for two-dimensional arrays:


In [76]:
grid = np.array([[1,2,3],[2,3,4]])

In [77]:
np.concatenate([grid,grid],axis=0)

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4]])

In [78]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [2, 3, 4, 2, 3, 4]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack
(vertical stack) and np.hstack (horizontal stack) functions

In [79]:
 x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],[6, 5, 4]])

In [80]:
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [81]:
y = np.array([[2],[2]])

In [82]:
np.hstack([y,grid])

array([[2, 9, 8, 7],
       [2, 6, 5, 4]])

Splitting of arrays
-------------------
The opposite of concatenation is splitting, which is implemented by the functions
np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices
giving the split points:

In [83]:
x = [1,2,3,4,5,6,7,8,9]
x1,x2,x3 = np.split(x,[3,6])
print(x1,x2,x3)

[1 2 3] [4 5 6] [7 8 9]


In [84]:
grid = np.arange(16).reshape((4,4))

In [85]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
upper,lower = np.vsplit(grid,[2])

In [87]:
print("upper:", upper)
print('--------------------------------------------')
print('\nlower:', lower)

upper: [[0 1 2 3]
 [4 5 6 7]]
--------------------------------------------

lower: [[ 8  9 10 11]
 [12 13 14 15]]


In [88]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
left , right = np.hsplit(grid,[2])

In [90]:
print(left)
print('--------------------------------------------')
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
--------------------------------------------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
